version: '3'

services:
  spark:
    build:
      context: ./spark
      dockerfile: dockerfile-driver
    ports:
      - '8080:8080'
    volumes:
      - ".:/spark-files:rw"

  spark-worker-1:
    build:
      context: ./spark
      dockerfile: dockerfile-executor

  spark-worker-2:
    build:
      context: ./spark
      dockerfile: dockerfile-executor

  minio-import:
    container_name: minio
    build:
      context: ./storage
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
      - '9090:9090'
    env_file:
      - .env
