FROM docker.io/bitnami/spark:3.4

ENV SPARK_MODE=worker \
    SPARK_MASTER_URL=spark://spark:7077 \
    SPARK_WORKER_MEMORY=1G \
    SPARK_WORKER_CORES=1 \
    SPARK_RPC_AUTHENTICATION_ENABLED=no \
    SPARK_RPC_ENCRYPTION_ENABLED=no \
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no \
    SPARK_SSL_ENABLED=no \
    SPARK_USER=spark

CMD ["bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark:7077"]
