FROM docker.io/bitnami/spark:3.4

ENV SPARK_MODE=master \
    SPARK_RPC_AUTHENTICATION_ENABLED=no \
    SPARK_RPC_ENCRYPTION_ENABLED=no \
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no \
    SPARK_SSL_ENABLED=no \
    SPARK_USER=spark

CMD ["bin/spark-class", "org.apache.spark.deploy.master.Master"]
